package corredores.gui;

import corredores.logica.LogicaCorredor;
import corredores.tableModel.CorredoresTableModel;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;
import logicaParaFicheros.LogicaFicherosCSV;
import run.PaginaPrincipal;

/**
 *
 * @author USER
 */
public class GestionCorredores extends javax.swing.JDialog {

    LogicaFicherosCSV lf = new LogicaFicherosCSV();
    CorredoresTableModel ctm;
    TableRowSorter<CorredoresTableModel> sorter;
    PaginaPrincipal paginaPrincipal;

    /**
     * Creates new form GestionCorredores
     *
     * @param parent
     * @param modal
     */
    public GestionCorredores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        paginaPrincipal = (PaginaPrincipal) parent;
        initComponents();
        this.setTitle("GESTIÓN DE CORREDORES");
        CargarTableModelCorredores();
    }

    //Método que rellena el listado de corredores
    public void CargarTableModelCorredores() {
        ctm = new CorredoresTableModel(LogicaCorredor.getListaCorredores());
        jTableCorredores.setModel(ctm);
        sorter = new TableRowSorter<>(ctm);
        jTableCorredores.setRowSorter(sorter);
        List<SortKey> sortkeys = new ArrayList<SortKey>();
        sortkeys.add(new SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortkeys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorredores = new javax.swing.JTable();
        jComboBoxFiltrar = new javax.swing.JComboBox<>();
        jTextFieldFiltrar = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGestionCorredores = new javax.swing.JMenu();
        jMenuItemAlta = new javax.swing.JMenuItem();
        jMenuItemBaja = new javax.swing.JMenuItem();
        jMenuItemModificacion = new javax.swing.JMenuItem();
        jMenuItemCarreras = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(575, 370));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jTableCorredores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCorredores);

        jComboBoxFiltrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por...", "Nombre", "DNI" }));

        jButtonFiltrar.setText("FILTRAR");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jTextFieldFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButtonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFiltrar))
                .addGap(19, 19, 19))
        );

        jMenuGestionCorredores.setText("    GESTION DE CORREDORES        ");

        jMenuItemAlta.setText("ALTA...");
        jMenuItemAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaActionPerformed(evt);
            }
        });
        jMenuGestionCorredores.add(jMenuItemAlta);

        jMenuItemBaja.setText("BAJA...");
        jMenuItemBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBajaActionPerformed(evt);
            }
        });
        jMenuGestionCorredores.add(jMenuItemBaja);

        jMenuItemModificacion.setText("MODIFICACION...");
        jMenuItemModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificacionActionPerformed(evt);
            }
        });
        jMenuGestionCorredores.add(jMenuItemModificacion);

        jMenuItemCarreras.setText("SUS CARRERAS...");
        jMenuItemCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarrerasActionPerformed(evt);
            }
        });
        jMenuGestionCorredores.add(jMenuItemCarreras);

        jMenuBar1.add(jMenuGestionCorredores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        if (jComboBoxFiltrar.getSelectedItem().equals("Nombre")) {
            RowFilter<CorredoresTableModel, Integer> rf = RowFilter.regexFilter(jTextFieldFiltrar.getText(), 0);
            sorter.setRowFilter(rf);
        } else if (jComboBoxFiltrar.getSelectedItem().equals("DNI")) {
            RowFilter<CorredoresTableModel, Integer> rf1 = RowFilter.regexFilter(jTextFieldFiltrar.getText(), 1);
            sorter.setRowFilter(rf1);
        }
        jTextFieldFiltrar.setText("");
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jMenuItemAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaActionPerformed
        DatosCorredor datosCorredor = new DatosCorredor(paginaPrincipal, true);
        datosCorredor.setVisible(true);
        ctm.fireTableDataChanged();
    }//GEN-LAST:event_jMenuItemAltaActionPerformed

    private void jMenuItemBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBajaActionPerformed
        try {
            int seleccion = jTableCorredores.convertRowIndexToModel(jTableCorredores.getSelectedRow());
            int opcion = JOptionPane.showConfirmDialog(this, "¿Desea eliminar al corredor?", "BORRADO", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                LogicaCorredor.getListaCorredores().remove(seleccion);
                lf.abrirFicheroCSVEscrituraCorredor("ficheros" + File.separator + "corredor.csv", LogicaCorredor.getListaCorredores());
                JOptionPane.showMessageDialog(this, "Corredor eliminado", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                ctm.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar", "ERROR", JOptionPane.ERROR);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado corredor", "", JOptionPane.INFORMATION_MESSAGE);
        }
        jTableCorredores.clearSelection();
    }//GEN-LAST:event_jMenuItemBajaActionPerformed

    private void jMenuItemModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificacionActionPerformed
        try {
            int seleccion = jTableCorredores.convertRowIndexToModel(jTableCorredores.getSelectedRow());
            ModificarDatos modificarDatos = new ModificarDatos(paginaPrincipal,
                    true, LogicaCorredor.getListaCorredores().get(seleccion));
            modificarDatos.setVisible(true);
            lf.abrirFicheroCSVEscrituraCorredor("ficheros" + File.separator + "corredor.csv", LogicaCorredor.getListaCorredores());
            ctm.fireTableDataChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado corredor", "", JOptionPane.INFORMATION_MESSAGE);
        }
        jTableCorredores.clearSelection();
    }//GEN-LAST:event_jMenuItemModificacionActionPerformed

    private void jMenuItemCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarrerasActionPerformed
        try {
            int seleccion = jTableCorredores.convertRowIndexToModel(jTableCorredores.getSelectedRow());
            CarrerasDelCorredor carrerasDelCorredor = new CarrerasDelCorredor(paginaPrincipal, true,
                    LogicaCorredor.getListaCorredores().get(seleccion));
            carrerasDelCorredor.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado corredor", "", JOptionPane.INFORMATION_MESSAGE);
        }
        jTableCorredores.clearSelection();
    }//GEN-LAST:event_jMenuItemCarrerasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JComboBox<String> jComboBoxFiltrar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGestionCorredores;
    private javax.swing.JMenuItem jMenuItemAlta;
    private javax.swing.JMenuItem jMenuItemBaja;
    private javax.swing.JMenuItem jMenuItemCarreras;
    private javax.swing.JMenuItem jMenuItemModificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCorredores;
    private javax.swing.JTextField jTextFieldFiltrar;
    // End of variables declaration//GEN-END:variables
}
