package carreras.gui;

import carreras.dto.Carrera;
import carreras.logica.LogicaCarreras;
import carreras.tableModel.CarrerasTableModel;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;
import org.openide.util.Exceptions;

/**
 *
 * @author USER
 */
public class CarrerasFinalizadas extends javax.swing.JDialog {

    CarrerasTableModel ctm;
    TableRowSorter<CarrerasTableModel> sorter;

    /**
     * Creates new form CarrerasFinalizadas
     */
    public CarrerasFinalizadas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("CARRERAS YA FINALIZADAS");
        cargarTabla();
    }

    public void cargarTabla() {
        ctm = new CarrerasTableModel(LogicaCarreras.getListaCarrerasFinalizadas());
        jTableFinalizadas.setModel(ctm);
        sorter = new TableRowSorter<>(ctm);
        jTableFinalizadas.setRowSorter(sorter);
        List<RowSorter.SortKey> sortKeys = new ArrayList<RowSorter.SortKey>();
        sortKeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortKeys);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFinalizadas = new javax.swing.JTable();
        jButtonVerInforme = new javax.swing.JButton();
        jComboBoxFiltrar = new javax.swing.JComboBox<>();
        jTextFieldFiltrar = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jTableFinalizadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableFinalizadas);
        if (jTableFinalizadas.getColumnModel().getColumnCount() > 0) {
            jTableFinalizadas.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(CarrerasFinalizadas.class, "CarrerasFinalizadas.jTableFinalizadas.columnModel.title0")); // NOI18N
            jTableFinalizadas.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(CarrerasFinalizadas.class, "CarrerasFinalizadas.jTableFinalizadas.columnModel.title1")); // NOI18N
            jTableFinalizadas.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(CarrerasFinalizadas.class, "CarrerasFinalizadas.jTableFinalizadas.columnModel.title2")); // NOI18N
            jTableFinalizadas.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(CarrerasFinalizadas.class, "CarrerasFinalizadas.jTableFinalizadas.columnModel.title3")); // NOI18N
        }

        jButtonVerInforme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonVerInforme.setText(org.openide.util.NbBundle.getMessage(CarrerasFinalizadas.class, "CarrerasFinalizadas.jButtonVerInforme.text")); // NOI18N
        jButtonVerInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerInformeActionPerformed(evt);
            }
        });

        jComboBoxFiltrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por...", "Nombre", "Lugar" }));

        jTextFieldFiltrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFiltrar.setText(org.openide.util.NbBundle.getMessage(CarrerasFinalizadas.class, "CarrerasFinalizadas.jTextFieldFiltrar.text")); // NOI18N

        jButtonFiltrar.setText(org.openide.util.NbBundle.getMessage(CarrerasFinalizadas.class, "CarrerasFinalizadas.jButtonFiltrar.text")); // NOI18N
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonVerInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFiltrar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVerInforme)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFiltrar)))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerInformeActionPerformed
        int num = jTableFinalizadas.convertRowIndexToModel(jTableFinalizadas.getSelectedRow());
        Carrera carrera = LogicaCarreras.getListaCarrerasFinalizadas().get(num);
        String ruta = "ficheros" + File.separator + "informeFinalizadas" + File.separator
                + carrera.getNomCarrera().trim().concat(carrera.getLugar().trim()) + ".csv";
        try {
            Desktop.getDesktop().open(new File(ruta));
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
        jTableFinalizadas.clearSelection();
    }//GEN-LAST:event_jButtonVerInformeActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        if (jComboBoxFiltrar.getSelectedItem().equals("Nombre")) {
            RowFilter<CarrerasTableModel, Integer> rf = RowFilter.regexFilter(jTextFieldFiltrar.getText(), 0);
            sorter.setRowFilter(rf);
        } else if (jComboBoxFiltrar.getSelectedItem().equals("Lugar")) {
            RowFilter<CarrerasTableModel, Integer> rf1 = RowFilter.regexFilter(jTextFieldFiltrar.getText(), 2);
            sorter.setRowFilter(rf1);
        }
        jTextFieldFiltrar.setText("");
    }//GEN-LAST:event_jButtonFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonVerInforme;
    private javax.swing.JComboBox<String> jComboBoxFiltrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFinalizadas;
    private javax.swing.JTextField jTextFieldFiltrar;
    // End of variables declaration//GEN-END:variables
}
