package carreras.gui;

import carreras.dto.Carrera;
import corredores.dto.Corredor;
import corredores.dto.Participante;
import corredores.logica.LogicaCorredor;
import corredores.tableModel.CorredoresTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;
import logicaParaFicheros.LogicaFicherosCSV;
import run.PaginaPrincipal;

/**
 *
 * @author USER
 */
public class CorredoresParaCarrera extends javax.swing.JDialog {

    CorredoresTableModel ctm;
    TableRowSorter<CorredoresTableModel> sorter;
    PaginaPrincipal paginaPrincipal;
    Carrera carrera;
    LogicaFicherosCSV lf = new LogicaFicherosCSV();
    /**
     * Creates new form CorredoresParaCarrera
     *
     * @param parent
     * @param modal
     * @param carrera
     */
    public CorredoresParaCarrera(java.awt.Frame parent, boolean modal, Carrera carrera) {
        super(parent, modal);
        paginaPrincipal = (PaginaPrincipal) parent;
        initComponents();
        cargarTableModelCorredoresParaCarrera();
        this.carrera = carrera;
        this.setTitle("CORREDORES PARA  " + carrera.getNomCarrera().toUpperCase());
    }

    public void cargarTableModelCorredoresParaCarrera() {
        ctm = new CorredoresTableModel(LogicaCorredor.getListaCorredores());
        jTableCorredorParaCarrera.setModel(ctm);
        sorter = new TableRowSorter<>(ctm);
        jTableCorredorParaCarrera.setRowSorter(sorter);
        List<RowSorter.SortKey> sortkeys = new ArrayList<RowSorter.SortKey>();
        sortkeys.add(new RowSorter.SortKey(0, SortOrder.ASCENDING));
        sorter.setSortKeys(sortkeys);
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorredorParaCarrera = new javax.swing.JTable();
        jToggleButtonAgregarCorredor = new javax.swing.JToggleButton();
        jToggleButtonSalir = new javax.swing.JToggleButton();
        jComboBoxFiltrar = new javax.swing.JComboBox<>();
        jTextFieldFiltrar = new javax.swing.JTextField();
        jToggleButtonFiltrar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCorredorParaCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCorredorParaCarrera);

        jToggleButtonAgregarCorredor.setText(org.openide.util.NbBundle.getMessage(CorredoresParaCarrera.class, "CorredoresParaCarrera.jToggleButtonAgregarCorredor.text")); // NOI18N
        jToggleButtonAgregarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAgregarCorredorActionPerformed(evt);
            }
        });

        jToggleButtonSalir.setText(org.openide.util.NbBundle.getMessage(CorredoresParaCarrera.class, "CorredoresParaCarrera.jToggleButtonSalir.text")); // NOI18N
        jToggleButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSalirActionPerformed(evt);
            }
        });

        jComboBoxFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar por...", "Nombre", "DNI" }));

        jTextFieldFiltrar.setText(org.openide.util.NbBundle.getMessage(CorredoresParaCarrera.class, "CorredoresParaCarrera.jTextFieldFiltrar.text")); // NOI18N

        jToggleButtonFiltrar.setText(org.openide.util.NbBundle.getMessage(CorredoresParaCarrera.class, "CorredoresParaCarrera.jToggleButtonFiltrar.text")); // NOI18N
        jToggleButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jToggleButtonAgregarCorredor, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jToggleButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxFiltrar, 0, 134, Short.MAX_VALUE)
                            .addComponent(jTextFieldFiltrar)
                            .addComponent(jToggleButtonFiltrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonAgregarCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonFiltrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonFiltrarActionPerformed
        if (jComboBoxFiltrar.getSelectedItem().equals("Nombre")) {
            RowFilter<CorredoresTableModel, Integer> rf = RowFilter.regexFilter(jTextFieldFiltrar.getText(), 0);
            sorter.setRowFilter(rf);
        }
        if (jComboBoxFiltrar.getSelectedItem().equals("DNI")) {
            RowFilter<CorredoresTableModel, Integer> rf1 = RowFilter.regexFilter(jTextFieldFiltrar.getText(), 1);
            sorter.setRowFilter(rf1);
        }
        jTextFieldFiltrar.setText("");
    }//GEN-LAST:event_jToggleButtonFiltrarActionPerformed

    private void jToggleButtonAgregarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAgregarCorredorActionPerformed
        try {
            int seleccion = jTableCorredorParaCarrera.convertRowIndexToModel(jTableCorredorParaCarrera.getSelectedRow());
            Corredor corredor = LogicaCorredor.getListaCorredores().get(seleccion);
            Participante participante = new Participante(corredor.getNombre());
            int dor = carrera.getListaDorsales().get(0);
            carrera.getListaDorsales().remove(0);
            participante.setDorsal(String.valueOf(dor));
            if (!carrera.getListaParticipantes().contains(participante)) {
                carrera.getListaParticipantes().add(participante);
                JOptionPane.showMessageDialog(this, "Asignado dorsal: " + dor);
                String ruta = "ficheros/participantes/"+carrera.getNomCarrera()+".csv";
                lf.abrirFicheroCSVEscrituraParticipantes(ruta, carrera.getListaParticipantes());
                corredor.getInscripciones().add(carrera);
            } else {
                JOptionPane.showMessageDialog(this, "El corredor ya está inscrito", "", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No ha seleccionado corredor");
        }
        jTableCorredorParaCarrera.clearSelection();
    }//GEN-LAST:event_jToggleButtonAgregarCorredorActionPerformed

    private void jToggleButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSalirActionPerformed
         this.dispose();
    }//GEN-LAST:event_jToggleButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxFiltrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCorredorParaCarrera;
    private javax.swing.JTextField jTextFieldFiltrar;
    private javax.swing.JToggleButton jToggleButtonAgregarCorredor;
    private javax.swing.JToggleButton jToggleButtonFiltrar;
    private javax.swing.JToggleButton jToggleButtonSalir;
    // End of variables declaration//GEN-END:variables
}
