package carreras.gui;

import carreras.dto.Carrera;
import carreras.logica.LogicaCarreras;
import carreras.tableModel.CarrerasTableModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import logicaParaFicheros.LogicaFicherosCSV;
import logicaParaFicheros.LogicaFicherosObjetos;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;
import run.PaginaPrincipal;

/**
 *
 * @author USER
 */
public class DatosCarrera extends javax.swing.JDialog {

    PaginaPrincipal paginaPrincipal;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    LogicaCarreras logicaCarrera = new LogicaCarreras();
    LogicaFicherosCSV lf = new LogicaFicherosCSV();
    LogicaFicherosObjetos lfo = new LogicaFicherosObjetos();
    CarrerasTableModel ctm = new CarrerasTableModel(LogicaCarreras.getListaCarreras());
    Carrera c;
    List<String> dorsales = new ArrayList<String>();

    /**
     * Creates new form DatosCarrera
     *
     * @param parent
     * @param modal
     */
    public DatosCarrera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        paginaPrincipal = (PaginaPrincipal) parent;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("DATOS PARA LA CARRERA");
        jButtonRegistrarCarrera.setEnabled(false);
        ValidationGroup group = validationPanelCarreras.getValidationGroup();
        group.add(jTextFieldLugarCarrera, StringValidators.REQUIRE_NON_EMPTY_STRING);
        group.add(jTextFieldNombreCarrera, StringValidators.REQUIRE_NON_EMPTY_STRING);
        validationPanelCarreras.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent ce) {
                if (validationPanelCarreras.getProblem() == null) {
                    jButtonRegistrarCarrera.setEnabled(true);
                } else {
                    jButtonRegistrarCarrera.setEnabled(false);
                }
            }
        });
    }

    /**
     * Método que crea una carrera, a partir de los contenidos en las vistas del
     * panel.
     *
     * @return una carrera(object).
     */
    private Carrera crearCarrera() {
        String nombre = jTextFieldNombreCarrera.getText();
        Date f = (Date) jSpinnerFechaCarrera.getValue();
        String fecha = sdf.format(f);
        String lugar = jTextFieldLugarCarrera.getText();
        int max = (int) jSpinnerMaxParticipantes.getValue();
        Carrera carrera = new Carrera(nombre, fecha, lugar, max);
        return carrera;
    }

    /**
     * Método que nos da opción de introducir un nuevo registro. Opción yes
     * prepara las vistas para nuevos registros, dejandolos vacios y en caso
     * contrario destruye el panel.
     */
    private void masRegistros() {
        int respuesta = JOptionPane.showConfirmDialog(this, "NUEVA CARRERA", "", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            jTextFieldNombreCarrera.setText("");
            jTextFieldLugarCarrera.setText("");
            jSpinnerMaxParticipantes.setValue(0);
        } else {
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNombreCarrera = new javax.swing.JTextField();
        jSpinnerFechaCarrera = new javax.swing.JSpinner();
        jTextFieldLugarCarrera = new javax.swing.JTextField();
        jSpinnerMaxParticipantes = new javax.swing.JSpinner();
        jButtonRegistrarCarrera = new javax.swing.JButton();
        validationPanelCarreras = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(DatosCarrera.class, "DatosCarrera.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(DatosCarrera.class, "DatosCarrera.jLabel2.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(DatosCarrera.class, "DatosCarrera.jLabel3.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(org.openide.util.NbBundle.getMessage(DatosCarrera.class, "DatosCarrera.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText(org.openide.util.NbBundle.getMessage(DatosCarrera.class, "DatosCarrera.jLabel5.text")); // NOI18N

        jTextFieldNombreCarrera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNombreCarrera.setText(org.openide.util.NbBundle.getMessage(DatosCarrera.class, "DatosCarrera.Nombre.text")); // NOI18N
        jTextFieldNombreCarrera.setName("Nombre"); // NOI18N

        jSpinnerFechaCarrera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinnerFechaCarrera.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1543713684888L), null, java.util.Calendar.DAY_OF_MONTH));

        jTextFieldLugarCarrera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldLugarCarrera.setText(org.openide.util.NbBundle.getMessage(DatosCarrera.class, "DatosCarrera.Lugar.text")); // NOI18N
        jTextFieldLugarCarrera.setName("Lugar"); // NOI18N

        jSpinnerMaxParticipantes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSpinnerMaxParticipantes.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButtonRegistrarCarrera.setText(org.openide.util.NbBundle.getMessage(DatosCarrera.class, "DatosCarrera.jButtonRegistrarCarrera.text")); // NOI18N
        jButtonRegistrarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarCarreraActionPerformed(evt);
            }
        });

        validationPanelCarreras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        validationPanelCarreras.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreCarrera)
                            .addComponent(jSpinnerFechaCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextFieldLugarCarrera)
                            .addComponent(jSpinnerMaxParticipantes)
                            .addComponent(jButtonRegistrarCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(validationPanelCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(140, 140, 140)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(validationPanelCarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerFechaCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLugarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerMaxParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegistrarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarCarreraActionPerformed

        c = crearCarrera();
        if (LogicaCarreras.getListaCarreras().contains(c)) {
            JOptionPane.showMessageDialog(this, "La carrera ya existe", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (logicaCarrera.agregarCarrera(c)) {
                lf.abrirFicheroCSVEscrituraCarrera("ficheros/carreras.csv", LogicaCarreras.getListaCarreras());
                // lfo.abrirFicheroObjetosEscrituraCarreras("ficheros/carreras.dat", LogicaCarreras.getListaCarreras());
                JOptionPane.showMessageDialog(this, "Carrera registrada", "CONFIRMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                masRegistros();
            } else {
                JOptionPane.showMessageDialog(this, "ERROR AL REGISTRAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonRegistrarCarreraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerFechaCarrera;
    private javax.swing.JSpinner jSpinnerMaxParticipantes;
    private javax.swing.JTextField jTextFieldLugarCarrera;
    private javax.swing.JTextField jTextFieldNombreCarrera;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanelCarreras;
    // End of variables declaration//GEN-END:variables
}
